#!/bin/bash

# Common functions for Azure App Service deployment scripts
# Source this file in other scripts: source "$(dirname "$0")/common.sh"

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging functions
log_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

log_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

log_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

log_error() {
    echo -e "${RED}❌ $1${NC}"
}

log_header() {
    echo ""
    echo -e "${BLUE}========================================${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}========================================${NC}"
    echo ""
}

# Check if user is logged into Azure
check_azure_login() {
    log_info "Checking Azure login status..."
    if ! az account show &> /dev/null; then
        log_error "Not logged into Azure. Please run 'az login' first."
        exit 1
    fi
    log_success "Azure login verified"
}

# Check if Azure CLI is installed
check_azure_cli() {
    if ! command -v az &> /dev/null; then
        log_error "Azure CLI is not installed. Please install it from https://docs.microsoft.com/en-us/cli/azure/install-azure-cli"
        exit 1
    fi
    log_success "Azure CLI found: $(az version --query '"azure-cli"' -o tsv)"
}

# Check if GitHub CLI is installed
check_github_cli() {
    if ! command -v gh &> /dev/null; then
        log_warning "GitHub CLI is not installed. You'll need to manually add secrets to GitHub."
        log_info "Install from: https://cli.github.com/"
        return 1
    fi
    log_success "GitHub CLI found"
    return 0
}

# Prompt for user input with default value
prompt_input() {
    local prompt_text=$1
    local default_value=$2
    local user_input

    if [ -n "$default_value" ]; then
        read -p "$(echo -e ${BLUE}$prompt_text ${NC}[${GREEN}$default_value${NC}]: )" user_input
        echo "${user_input:-$default_value}"
    else
        read -p "$(echo -e ${BLUE}$prompt_text: ${NC})" user_input
        echo "$user_input"
    fi
}

# Prompt for confirmation (defaults to yes)
prompt_confirm() {
    local prompt_text=$1
    local response

    while true; do
        read -p "$(echo -e ${YELLOW}$prompt_text ${NC}[${GREEN}yes${NC}]: )" response
        # Default to yes if empty
        response=${response:-yes}
        case $response in
            [Yy]* | yes | YES ) return 0;;
            [Nn]* | no | NO ) return 1;;
            * ) echo "Please answer yes or no.";;
        esac
    done
}

# Validate subscription ID format
validate_subscription_id() {
    local subscription_id=$1
    if [[ ! $subscription_id =~ ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$ ]]; then
        log_error "Invalid subscription ID format"
        return 1
    fi
    return 0
}

# Validate resource name (Azure naming rules)
validate_resource_name() {
    local name=$1
    local max_length=${2:-24}
    
    if [[ ! $name =~ ^[a-z0-9-]+$ ]]; then
        log_error "Invalid resource name. Use only lowercase letters, numbers, and hyphens."
        return 1
    fi
    
    if [ ${#name} -gt $max_length ]; then
        log_error "Resource name too long. Maximum length is $max_length characters."
        return 1
    fi
    
    return 0
}

# Get current Azure subscription
get_current_subscription() {
    az account show --query id -o tsv
}

# Get current Azure subscription name
get_current_subscription_name() {
    az account show --query name -o tsv
}

# Check if resource group exists
resource_group_exists() {
    local rg_name=$1
    az group exists --name "$rg_name" -o tsv
}

# Create resource group if it doesn't exist
create_resource_group_if_not_exists() {
    local rg_name=$1
    local location=$2
    
    if [ "$(resource_group_exists "$rg_name")" = "true" ]; then
        log_info "Resource group '$rg_name' already exists"
        return 0
    fi
    
    log_info "Creating resource group '$rg_name' in '$location'..."
    if az group create --name "$rg_name" --location "$location" --output none; then
        log_success "Resource group '$rg_name' created"
        return 0
    else
        log_error "Failed to create resource group '$rg_name'"
        return 1
    fi
}

# Export environment variables to file
export_env_vars() {
    local env_file=$1
    shift
    local vars=("$@")
    
    log_info "Exporting environment variables to $env_file..."
    
    {
        echo "# Generated by bootstrap script on $(date)"
        echo "# DO NOT COMMIT THIS FILE TO VERSION CONTROL"
        echo ""
        for var in "${vars[@]}"; do
            echo "$var"
        done
    } > "$env_file"
    
    log_success "Environment variables exported to $env_file"
}

# Display next steps
display_next_steps() {
    local steps=$1
    
    log_header "📋 Next Steps"
    echo -e "${YELLOW}$steps${NC}"
    echo ""
}
